# Generated by Django 5.2.4 on 2025-07-27 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('aadhar', models.CharField(max_length=12, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
                ('district', models.CharField(max_length=40, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('address', models.TextField(null=True)),
                ('occupation', models.CharField(max_length=40, null=True)),
                ('income', models.BigIntegerField(null=True)),
                ('marital', models.CharField(max_length=20, null=True)),
                ('caste', models.CharField(max_length=10, null=True)),
                ('disability', models.CharField(max_length=10, null=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
