# Generated by Django 5.2.4 on 2025-08-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='disability_required',
            field=models.CharField(choices=[('Any', 'Any'), ('Yes', 'Yes'), ('None', 'None')], default='Any', max_length=30),
        ),
    ]
