# Generated by Django 5.2.4 on 2025-08-03 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0002_alter_scheme_disability_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='eligible_castes',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('SC,ST', 'SCST'), ('OBC', 'OBC'), ('General', 'General'), ('EWS', 'EWS')], default='Any', max_length=255),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='schemeapp.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
