# Generated by Django 5.2.4 on 2025-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0004_userprofile_rural_userprofile_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='scheme_logo/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('eligible_castes', models.CharField(blank=True, help_text='Comma-separated values: SC,ST,OBC,General', max_length=255)),
                ('income_limit', models.FloatField(blank=True, help_text='Annual income upper limit in INR', null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=10)),
                ('required_education', models.CharField(blank=True, help_text='e.g., 10th Pass, Graduate, ITI', max_length=255)),
                ('disability_required', models.BooleanField(default=False)),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Any', 'Any')], default='Any', max_length=20)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('required_documents', models.TextField(blank=True, help_text='List required documents, separated by commas')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='scheme_docs/')),
            ],
        ),
    ]
