# Generated by Django 5.2.4 on 2025-08-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0005_states_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='required_documents',
        ),
        migrations.CreateModel(
            name='RequiredDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='List required documents, separated by commas', max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='schemeapp.scheme')),
            ],
        ),
    ]
