# Generated by Django 5.2.4 on 2025-07-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0005_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='logo',
        ),
        migrations.AddField(
            model_name='scheme',
            name='benefits',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EligibilityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('expected_answer', models.CharField(max_length=20)),
                ('field_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('boolean', 'Yes/No'), ('text', 'Text'), ('number', 'Number')], max_length=20)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='schemeapp.scheme')),
            ],
        ),
    ]
