# Generated by Django 5.2.4 on 2025-07-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0006_remove_scheme_logo_scheme_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='attachment',
            field=models.FileField(blank=True, default=1, upload_to='scheme_docs/'),
            preserve_default=False,
        ),
    ]
