# Generated by Django 5.2.4 on 2025-07-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0007_alter_scheme_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='income_limit',
            field=models.BigIntegerField(blank=True, help_text='Annual income upper limit in INR', null=True),
        ),
    ]
