# Generated by Django 5.2.4 on 2025-08-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0008_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reasons', to='schemeapp.application')),
                ('document_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemeapp.uploadeddocument')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfulApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printout', models.FileField(upload_to='successful/printouts/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemeapp.application')),
            ],
        ),
    ]
