# Generated by Django 5.2.4 on 2025-08-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0009_rejectionreason_successfulapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RejectionReason',
        ),
    ]
