# Generated by Django 5.2.4 on 2025-08-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0010_uploadeddocument_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='required_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_document', to='schemeapp.requireddocuments'),
        ),
    ]
