# Generated by Django 5.2.4 on 2025-08-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0010_alter_scheme_required_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='required_education',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('below_10', 'Below 10th'), ('10', '10th'), ('12', '12th'), ('diploma', 'Diploma'), ('ug', 'Undergraduate (UG)'), ('pg', 'Postgraduate (PG)'), ('phd', 'PhD / Doctorate'), ('other', 'Other')], default='Any', help_text='Select the minimum educational qualification required', max_length=20),
        ),
    ]
