# Generated by Django 5.2.4 on 2025-08-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0013_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityquestion',
            name='expected_answer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
