# Generated by Django 5.2.4 on 2025-08-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0014_alter_eligibilityquestion_expected_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='income_limit',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual income upper limit in INR', null=True),
        ),
    ]
