# Generated by Django 5.2.4 on 2025-08-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0015_alter_scheme_income_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='eligible_castes',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('SC,ST', 'SC,ST'), ('OBC', 'OBC'), ('General', 'General'), ('EWS', 'EWS')], default='Any', max_length=255),
        ),
    ]
