# Generated by Django 5.2.4 on 2025-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0016_alter_scheme_eligible_castes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityquestion',
            name='type',
            field=models.CharField(choices=[('boolean', 'Yes/No')], max_length=20),
        ),
    ]
